### PR TITLE
#19 converter

### PR DESCRIPTION
**Pull request by r-yamada1998**

### CODE REVIEW

**Review by KaoruNishikawa — CHANGES_REQUESTED** [review]
Quick suggestions:

- FITS header conversion method in the following line should be `tostring`, not `to_string`.

    https://github.com/a-lab-nagoya/xarray-cube/blob/7141b93cc826fe7c8d916f27104f8718404e3ada/xarray_cube/converter.py#L13

- The name of FITS `ImageHDU` class seems invalid (should start with capital letter).

    https://github.com/a-lab-nagoya/xarray-cube/blob/7141b93cc826fe7c8d916f27104f8718404e3ada/xarray_cube/converter.py#L23

**Review by KaoruNishikawa — APPROVED** [review]

**Comment by KaoruNishikawa** [comment]
The `hdu` property of SpectralCube modifies the FITS header comments like below; is this behaviour OK for this project?

https://github.com/a-lab-nagoya/xarray-cube/blob/85dbf94673b21dfc6585d0e3559e580084f9b098/xarray_cube/converter.py#L13

```python
>>> cube.hdu.header
SIMPLE  =                    T / conforms to FITS standard
...
>>> cube.header
SIMPLE  =                    T /Standard FITS
...
```

If not, please use `cube.header` instead, otherwise let me know as this difference affects test script's implementation.

**Comment by astropenguin** [comment]
It seems that `cube.hdu` creates a new primary HDU while `cube.header` does not. So I think we should use the latter.

https://github.com/radio-astro-tools/spectral-cube/blob/9681cca50c1ba9c23a9eee33380afa5c9f1a9f0d/spectral_cube/spectral_cube.py#L2441

https://github.com/radio-astro-tools/spectral-cube/blob/9681cca50c1ba9c23a9eee33380afa5c9f1a9f0d/spectral_cube/spectral_cube.py#L2456

**Comment by r-yamada1998** [comment]
cube.headerを用いた場合は、headerの中身によってはheaderを書き換えたものを返すように思われます。特に、cunit3のvalueがない場合などは、自動的にheaderにcunit3のvalueを追加する仕様です。いずれの方法を選んでもオリジナルから変更が行われるという点では大差ないように思われますが、どのようにいたしましょうか？

**Review by astropenguin — APPROVED** [review]
Thank you for your contribution! It looks good to me.

**Pull request merged**
